# ====================================================================
# 1. SILENCIAMENTO AGRESSIVO DE INFRAESTRUTURA
# ====================================================================
platform.observability.logging.defaults.org.springframework=ERROR
platform.observability.logging.defaults.org.hibernate=ERROR
platform.observability.logging.defaults.org.hibernate.orm.deprecation=OFF
platform.observability.logging.defaults.com.zaxxer.hikari=ERROR
platform.observability.logging.defaults.org.apache.catalina=ERROR
platform.observability.logging.defaults.org.apache.coyote=ERROR
platform.observability.logging.defaults.org.hibernate.validator=ERROR
platform.observability.logging.defaults.org.apache.kafka=ERROR

# ====================================================================
# 2. PADRAO DOS PACOTES DE NEGOCIO
# ====================================================================
platform.observability.logging.defaults.com.brunobs=INFO
platform.observability.logging.defaults.br.com.portalmanager.platform=INFO
