<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>br.com.portalmanager.platform.library</groupId>
        <artifactId>platform-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../../platform-parent/pom.xml</relativePath>
    </parent>

    <artifactId>platform-audit</artifactId>
    <packaging>jar</packaging>
    <name>platform-audit</name>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>br.com.portalmanager.platform.library</groupId>
                <artifactId>platform-libraries-bom</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>br.com.portalmanager.platform.library</groupId>
            <artifactId>platform-authorization</artifactId>
        </dependency>
        <dependency>
            <groupId>br.com.portalmanager.platform.library</groupId>
            <artifactId>platform-messaging</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aspectj</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>br.com.portalmanager.platform.library</groupId>
            <artifactId>platform-testing-database</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
